apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/memo-deploy.git
    targetRevision: dev
    path: helm/memo-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: memo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
