apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/memo-deploy.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: memo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
